version: '3'

dotenv: ['.env']

tasks:

  default:
    cmds:
      - task --list-all

  init:
    desc: initalize the workspace
    cmds:
      - npm i
      - cd dapp && npm i
      - npx tsc scripts/deploy.ts

  contracts-build:
    cmds:
      - solc -o build/contracts --include-path node_modules/ --bin --abi --asm-json --ast-compact-json --asm --overwrite contracts/*.sol
      # truffle compile

  contracts-deploy-local:
    desc: deploy contracts to ganache
    cmds:
      - npx hardhat run scripts/deploy.js --network localhost
      # truffle migrate
      # node ./scripts/deploy-contract.js

  contracts-test:
    cmds:
      - npx hardhat test
      # truffle test /test/Test*.js
